services:
  - type: web
    name: movie-base
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SYNC_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: RUN_SCHEDULER
        value: "true"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
